
package Visual;

import Control.InstalacionesData;
import Control.Utilitario;
import Entidades.Instalacion;
import Entidades.Masajista;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GestionInstalacion extends javax.swing.JInternalFrame {

    
    Color verdeLibre = new Color(200,242,183);
    Color rojoOcupado = new Color(245,164,164);
    
    InstalacionesData instalaciones = new InstalacionesData();
    Instalacion i = new Instalacion();
    
    private DefaultTableModel modeloT = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila, int columna){ 
        return false;
    }
    };
        private DefaultTableModel modeloTSec = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila, int columna){ 
        return false;
    }
    };
    public GestionInstalacion() {
        initComponents();
        cargarModelo();
        cargarModeloS();
        cargarTabla();
        cargarTablaS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPanelPrincipal = new javax.swing.JPanel();
        jpPanelInstalacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpPanelInfoI = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDetallesUso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio30M = new javax.swing.JTextField();
        txtUsos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbNuevo = new javax.swing.JButton();
        jbSubir = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jpPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaInstalaciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jpPanelBotones = new javax.swing.JPanel();
        jbBorrar = new javax.swing.JButton();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jpPanelInstalacionesD = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTablaInstalacionesLibres = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jpPanelEstado = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtEstado = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(0, 0));

        jpPanelPrincipal.setBackground(new java.awt.Color(102, 153, 255));

        jpPanelInstalacion.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelInstalacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Instalacion - ingreso de datos");

        jpPanelInfoI.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelInfoI.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNombre.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de la instalacion");

        txtDetallesUso.setToolTipText("Ingrese su funcion, que proposito cumple, etc.");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Detalles de usos");

        txtApto.setToolTipText("Ingrese para que publico puede ser apto su uso");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apto");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio X 30M ($)");

        txtPrecio30M.setToolTipText("Ingrese solo digitos");

        txtUsos.setToolTipText("Ingrese el fin o proposito de la instalacion");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usos");

        javax.swing.GroupLayout jpPanelInfoILayout = new javax.swing.GroupLayout(jpPanelInfoI);
        jpPanelInfoI.setLayout(jpPanelInfoILayout);
        jpPanelInfoILayout.setHorizontalGroup(
            jpPanelInfoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInfoILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelInfoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelInfoILayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInfoILayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio30M, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInfoILayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInfoILayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInfoILayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDetallesUso, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelInfoILayout.setVerticalGroup(
            jpPanelInfoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInfoILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelInfoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelInfoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDetallesUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelInfoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPanelInfoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio30M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelInfoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jbNuevo.setBackground(new java.awt.Color(204, 215, 255));
        jbNuevo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbNuevo.setForeground(new java.awt.Color(51, 51, 51));
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbSubir.setBackground(new java.awt.Color(153, 255, 153));
        jbSubir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbSubir.setForeground(new java.awt.Color(51, 51, 51));
        jbSubir.setText("Subir");
        jbSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubirActionPerformed(evt);
            }
        });

        jbActualizar.setBackground(new java.awt.Color(102, 204, 255));
        jbActualizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(51, 51, 51));
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSubir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPanelInstalacionLayout = new javax.swing.GroupLayout(jpPanelInstalacion);
        jpPanelInstalacion.setLayout(jpPanelInstalacionLayout);
        jpPanelInstalacionLayout.setHorizontalGroup(
            jpPanelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelInstalacionLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpPanelInstalacionLayout.createSequentialGroup()
                        .addComponent(jpPanelInfoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpPanelInstalacionLayout.setVerticalGroup(
            jpPanelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPanelInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpPanelInfoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPanelTabla.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelTabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtTablaInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaInstalaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaInstalacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaInstalaciones);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Instalaciones registradas");

        jpPanelBotones.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbBorrar.setBackground(new java.awt.Color(255, 153, 153));
        jbBorrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbBorrar.setForeground(new java.awt.Color(51, 51, 51));
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbAlta.setBackground(new java.awt.Color(255, 255, 153));
        jbAlta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbAlta.setForeground(new java.awt.Color(51, 51, 51));
        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setBackground(new java.awt.Color(255, 153, 204));
        jbBaja.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbBaja.setForeground(new java.awt.Color(51, 51, 51));
        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        txtID.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID");

        javax.swing.GroupLayout jpPanelBotonesLayout = new javax.swing.GroupLayout(jpPanelBotones);
        jpPanelBotones.setLayout(jpPanelBotonesLayout);
        jpPanelBotonesLayout.setHorizontalGroup(
            jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpPanelBotonesLayout.setVerticalGroup(
            jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpPanelTablaLayout = new javax.swing.GroupLayout(jpPanelTabla);
        jpPanelTabla.setLayout(jpPanelTablaLayout);
        jpPanelTablaLayout.setHorizontalGroup(
            jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                    .addGroup(jpPanelTablaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpPanelTablaLayout.setVerticalGroup(
            jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelTablaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(jpPanelTablaLayout.createSequentialGroup()
                        .addComponent(jpPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpPanelInstalacionesD.setBackground(new java.awt.Color(102, 213, 255));
        jpPanelInstalacionesD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("Instalaciones disponibles");

        jtTablaInstalacionesLibres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtTablaInstalacionesLibres);

        javax.swing.GroupLayout jpPanelInstalacionesDLayout = new javax.swing.GroupLayout(jpPanelInstalacionesD);
        jpPanelInstalacionesD.setLayout(jpPanelInstalacionesDLayout);
        jpPanelInstalacionesDLayout.setHorizontalGroup(
            jpPanelInstalacionesDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInstalacionesDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelInstalacionesDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpPanelInstalacionesDLayout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );
        jpPanelInstalacionesDLayout.setVerticalGroup(
            jpPanelInstalacionesDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInstalacionesDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jbSalir.setBackground(new java.awt.Color(255, 51, 51));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(51, 51, 51));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jpPanelEstado.setBackground(new java.awt.Color(102, 153, 255));
        jpPanelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado de la instalacion");

        jtEstado.setEditable(false);
        jtEstado.setBackground(new java.awt.Color(200, 242, 183));
        jtEstado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jtEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtEstado.setText("Apto para su uso");
        jtEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jpPanelEstadoLayout = new javax.swing.GroupLayout(jpPanelEstado);
        jpPanelEstado.setLayout(jpPanelEstadoLayout);
        jpPanelEstadoLayout.setHorizontalGroup(
            jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelEstadoLayout.setVerticalGroup(
            jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPanelPrincipalLayout = new javax.swing.GroupLayout(jpPanelPrincipal);
        jpPanelPrincipal.setLayout(jpPanelPrincipalLayout);
        jpPanelPrincipalLayout.setHorizontalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpPanelInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jpPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jpPanelInstalacionesD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
        );
        jpPanelPrincipalLayout.setVerticalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jpPanelInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpPanelInstalacionesD, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jpPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubirActionPerformed
        // TODO add your handling code here:
        if(validarCampos()== true){
            instalaciones.cargarInstalacion(i);
            cargarTabla();
            vaciarCampos();
            inhabilitarCampos();
            jbActualizar.setEnabled(false);
            jbSubir.setEnabled(true);
        }
    }//GEN-LAST:event_jbSubirActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        if(validarCampos()== true){
            instalaciones.modificarInstalacion(i);
            cargarTabla();
            vaciarCampos();
            cargarTablaS();
            jbActualizar.setEnabled(false);
            jbSubir.setEnabled(true);
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
        if(i.getCodIns() == -1){
            JOptionPane.showMessageDialog(null, "Seleccione una instalacion para borrar");
        }else{
            instalaciones.borrarInstalacion(i.getCodIns());
            cargarTabla();
            vaciarCampos();
            cargarTablaS();
            jbActualizar.setEnabled(false);
            jbSubir.setEnabled(true);
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jtTablaInstalacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaInstalacionesMouseClicked
        // TODO add your handling code here:
        
        cargarCampos();
        habilitarCampos();
        jbActualizar.setEnabled(true);
        jbSubir.setEnabled(false);
        
    }//GEN-LAST:event_jtTablaInstalacionesMouseClicked

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        
         dispose();
         
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
        
        if(i.getCodIns() == -1){
            JOptionPane.showMessageDialog(null, "Seleccione alguna instalacion");
            
        }else{
            instalaciones.darDeAlta(i.getCodIns());
            cargarTabla();
            cargarTablaS();
            vaciarCampos();
            jbActualizar.setEnabled(false);
            jbSubir.setEnabled(true);
        }
        
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
        
        if(i.getCodIns() == -1){
            JOptionPane.showMessageDialog(null, "Seleccione alguna instalacion");
        }else{
            instalaciones.darDeBaja(i.getCodIns());
            cargarTabla();
            cargarTablaS();
            vaciarCampos();
            jbActualizar.setEnabled(false);
            jbSubir.setEnabled(true);
        }
        
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        
        vaciarCampos();
        habilitarCampos();
        
    }//GEN-LAST:event_jbNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSubir;
    private javax.swing.JPanel jpPanelBotones;
    private javax.swing.JPanel jpPanelEstado;
    private javax.swing.JPanel jpPanelInfoI;
    private javax.swing.JPanel jpPanelInstalacion;
    private javax.swing.JPanel jpPanelInstalacionesD;
    private javax.swing.JPanel jpPanelPrincipal;
    private javax.swing.JPanel jpPanelTabla;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTable jtTablaInstalaciones;
    private javax.swing.JTable jtTablaInstalacionesLibres;
    private javax.swing.JTextField txtApto;
    private javax.swing.JTextField txtDetallesUso;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio30M;
    private javax.swing.JTextField txtUsos;
    // End of variables declaration//GEN-END:variables

//CAMPOS TEXTFIELD..........................................................    
    public void cargarModelo() {
        modeloT.addColumn("ID");
        modeloT.addColumn("Nombre");
        modeloT.addColumn("Detalles de uso");
        modeloT.addColumn("PrecioX30M");
        modeloT.addColumn("Usos");
        modeloT.addColumn("Apto");
        modeloT.addColumn("estado");
        jtTablaInstalaciones.setModel(modeloT);
    }

    public void cargarModeloS() {
        modeloTSec.addColumn("ID");
        modeloTSec.addColumn("Nombre");
        modeloTSec.addColumn("estado");
        jtTablaInstalacionesLibres.setModel(modeloTSec);
    }

    public void cargarTabla() {
        Utilitario.limpiarTabla(modeloT);
        for (Instalacion ins : instalaciones.mostrarInstalaciones()) {
            modeloT.addRow(new Object[]{ins.getCodIns(), ins.getNombre(), ins.getDetallesUso(), ins.getPrecio30M(), ins.getUsos(), ins.getApto(), ins.getEstado()});
        }
    }

    public void cargarTablaS() {
        Utilitario.limpiarTabla(modeloTSec);
        for (Instalacion ins : instalaciones.mostrarInstalacionesLibres()) {
            modeloTSec.addRow(new Object[]{ins.getCodIns(), ins.getNombre(), ins.getEstado()});
        }
    }

//CAMPOS TEXTFIELD..........................................................    
    private boolean validarCampos() {
        
        if (txtNombre.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Ingrese un nombre!!!", "Cuidado", JOptionPane.WARNING_MESSAGE);
            
        } else if (txtDetallesUso.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Ingrese Detalles de uso!!!", "Cuidado", JOptionPane.WARNING_MESSAGE);
            
        } else if (txtApto.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Ingrese para que es apto!!!", "Cuidado", JOptionPane.WARNING_MESSAGE);
            
        } else if (txtPrecio30M.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Ingrese el precio por media hora!!!", "Cuidado", JOptionPane.WARNING_MESSAGE);
            
        } else if (txtUsos.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Ingrese para que fin esta destinado su uso.EJ:(Relajacion)!!!", "Cuidado", JOptionPane.WARNING_MESSAGE);
            
        } else {
            try {
                String nombre = txtNombre.getText();
                String detallesUso = txtDetallesUso.getText();
                String apto = txtApto.getText();
                String usos = txtUsos.getText();
                int precio30M = Integer.parseInt(txtPrecio30M.getText());

                i.setNombre(nombre);
                i.setDetallesUso(detallesUso);
                i.setApto(apto);
                i.setPrecio30M(precio30M);
                i.setUsos(usos);
                i.setEstado(true);

                return true;
            } catch (java.lang.NumberFormatException error) {
                JOptionPane.showMessageDialog(null, "Ingrese el precio en el formato adecuado!!!", "Error en el formato",JOptionPane.ERROR_MESSAGE);
            }
        }

        return false;
    }

    private void vaciarCampos() {
        
        txtNombre.setText("");
        txtDetallesUso.setText("");
        txtApto.setText("");
        txtUsos.setText("");
        txtPrecio30M.setText("");
        txtID.setText("");
        jtEstado.setText("Para usar");
        jtEstado.setBackground(verdeLibre);
        jtTablaInstalaciones.clearSelection();
        jbAlta.setEnabled(true);
        jbBaja.setEnabled(true);
        i.setCodIns(-1);
        
    }

//METODO ACTUALIZAR..........................................................
    private void cargarCampos() {
        int filaS = jtTablaInstalaciones.getSelectedRow();
        String id = String.valueOf(jtTablaInstalaciones.getValueAt(filaS, 0));
        String nombre = String.valueOf(jtTablaInstalaciones.getValueAt(filaS, 1));
        String detallesUso = String.valueOf(jtTablaInstalaciones.getValueAt(filaS, 2));
        String precio30M = String.valueOf(jtTablaInstalaciones.getValueAt(filaS, 3));
        String usos = String.valueOf(jtTablaInstalaciones.getValueAt(filaS, 4));
        String apto = String.valueOf(jtTablaInstalaciones.getValueAt(filaS, 5));
        int idd = (Integer) jtTablaInstalaciones.getValueAt(filaS, 0);
        
        txtNombre.setText(nombre);
        txtDetallesUso.setText(detallesUso);
        txtApto.setText(apto);
        txtUsos.setText(usos);
        txtPrecio30M.setText(precio30M);
        txtID.setText(id);
        
        
        i.setCodIns(idd);
        
        
        //habilita e inhabilita segun el estado del objeto.
        boolean estados = Boolean.valueOf(jtTablaInstalaciones.getValueAt(filaS, 6).toString());
        if (estados == true) {
            
            jbAlta.setEnabled(false);
            jbBaja.setEnabled(true);
            jtEstado.setBackground(verdeLibre);
            jtEstado.setText("Apto para su uso");
            
        } else if (estados == false) {
            
            jbAlta.setEnabled(true);
            jbBaja.setEnabled(false);
            jtEstado.setBackground(rojoOcupado);
            jtEstado.setText("En reparaciones");
            
        }
    }

    private void inhabilitarCampos() {
        
        txtNombre.setEnabled(false);
        txtDetallesUso.setEnabled(false);
        txtApto.setEnabled(false);
        txtUsos.setEnabled(false);
        txtPrecio30M.setEnabled(false);
        
    }

    private void habilitarCampos() {
        
        txtNombre.setEnabled(true);
        txtDetallesUso.setEnabled(true);
        txtApto.setEnabled(true);
        txtUsos.setEnabled(true);
        txtPrecio30M.setEnabled(true);
        
    }
    
}
