
package Visual;

import Control.MasajistasData;
import Control.Utilitario;
import Entidades.Masajista;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GestionMasajista extends javax.swing.JInternalFrame {

    Color verdeActivo = new Color(200,242,183);
    Color rojoInactivo = new Color(245,164,164);
    
    
    
    MasajistasData masajistas = new MasajistasData();
    Masajista m = new Masajista();
    private DefaultTableModel modeloT = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila, int columna){ 
        return false;
    }
    };
    private DefaultTableModel modeloTSec= new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila, int columna){ 
        return false;
    }
    };
   
    public GestionMasajista() {
        initComponents();
        cargarModelo();
        cargarCombo();
        cargarTabla();
        cargarModeloS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPanelPrincipal = new javax.swing.JPanel();
        jpPanelMasajista = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpPanelInfoMasajista = new javax.swing.JPanel();
        txtMatricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpPanelBotones1 = new javax.swing.JPanel();
        jbNuevo = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbSubir = new javax.swing.JButton();
        jpPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaMasajistas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jpPanelBotones2 = new javax.swing.JPanel();
        jbBorrar = new javax.swing.JButton();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        jpPanelTablaSecundaria = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTablaMasajistaEspecialidad = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jcbEspecialidades = new javax.swing.JComboBox<>();
        jpPanelEstado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtEstado = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();

        jpPanelPrincipal.setBackground(new java.awt.Color(102, 153, 255));
        jpPanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 4));

        jpPanelMasajista.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelMasajista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jpPanelMasajista.setPreferredSize(new java.awt.Dimension(515, 230));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Masajista");

        jpPanelInfoMasajista.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelInfoMasajista.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Matricula");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre completo");

        txtNumeroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de Telefono");

        txtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Especialidad");

        javax.swing.GroupLayout jpPanelInfoMasajistaLayout = new javax.swing.GroupLayout(jpPanelInfoMasajista);
        jpPanelInfoMasajista.setLayout(jpPanelInfoMasajistaLayout);
        jpPanelInfoMasajistaLayout.setHorizontalGroup(
            jpPanelInfoMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInfoMasajistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelInfoMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelInfoMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInfoMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInfoMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInfoMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelInfoMasajistaLayout.setVerticalGroup(
            jpPanelInfoMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInfoMasajistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelInfoMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelInfoMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelInfoMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelInfoMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPanelBotones1.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelBotones1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jbNuevo.setBackground(new java.awt.Color(204, 204, 204));
        jbNuevo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.setToolTipText("");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbActualizar.setBackground(new java.awt.Color(102, 204, 255));
        jbActualizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbSubir.setBackground(new java.awt.Color(153, 255, 153));
        jbSubir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbSubir.setText("Subir");
        jbSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelBotones1Layout = new javax.swing.GroupLayout(jpPanelBotones1);
        jpPanelBotones1.setLayout(jpPanelBotones1Layout);
        jpPanelBotones1Layout.setHorizontalGroup(
            jpPanelBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelBotones1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelBotones1Layout.setVerticalGroup(
            jpPanelBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelBotones1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPanelMasajistaLayout = new javax.swing.GroupLayout(jpPanelMasajista);
        jpPanelMasajista.setLayout(jpPanelMasajistaLayout);
        jpPanelMasajistaLayout.setHorizontalGroup(
            jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addComponent(jpPanelInfoMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jpPanelBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jpPanelMasajistaLayout.setVerticalGroup(
            jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelMasajistaLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpPanelBotones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPanelInfoMasajista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jpPanelTabla.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelTabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpPanelTabla.setPreferredSize(new java.awt.Dimension(514, 251));

        jtTablaMasajistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaMasajistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaMasajistasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaMasajistas);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MASAJISTAS");

        jpPanelBotones2.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelBotones2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbBorrar.setBackground(new java.awt.Color(255, 153, 153));
        jbBorrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbAlta.setBackground(new java.awt.Color(255, 255, 153));
        jbAlta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setBackground(new java.awt.Color(255, 153, 204));
        jbBaja.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelBotones2Layout = new javax.swing.GroupLayout(jpPanelBotones2);
        jpPanelBotones2.setLayout(jpPanelBotones2Layout);
        jpPanelBotones2Layout.setHorizontalGroup(
            jpPanelBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelBotones2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelBotones2Layout.setVerticalGroup(
            jpPanelBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelBotones2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPanelTablaLayout = new javax.swing.GroupLayout(jpPanelTabla);
        jpPanelTabla.setLayout(jpPanelTablaLayout);
        jpPanelTablaLayout.setHorizontalGroup(
            jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelTablaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpPanelBotones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpPanelTablaLayout.setVerticalGroup(
            jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jpPanelBotones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpPanelTablaSecundaria.setBackground(new java.awt.Color(102, 153, 255));
        jpPanelTablaSecundaria.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtTablaMasajistaEspecialidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtTablaMasajistaEspecialidad);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar por especialidad");

        jcbEspecialidades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcbEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especialidades" }));
        jcbEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEspecialidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelTablaSecundariaLayout = new javax.swing.GroupLayout(jpPanelTablaSecundaria);
        jpPanelTablaSecundaria.setLayout(jpPanelTablaSecundariaLayout);
        jpPanelTablaSecundariaLayout.setHorizontalGroup(
            jpPanelTablaSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelTablaSecundariaLayout.createSequentialGroup()
                .addGroup(jpPanelTablaSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelTablaSecundariaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelTablaSecundariaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpPanelTablaSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelTablaSecundariaLayout.setVerticalGroup(
            jpPanelTablaSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelTablaSecundariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpPanelEstado.setBackground(new java.awt.Color(102, 153, 255));
        jpPanelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado del masajista");

        jtEstado.setBackground(new java.awt.Color(200, 242, 180));
        jtEstado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jtEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtEstado.setText("Libre");
        jtEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelEstadoLayout = new javax.swing.GroupLayout(jpPanelEstado);
        jpPanelEstado.setLayout(jpPanelEstadoLayout);
        jpPanelEstadoLayout.setHorizontalGroup(
            jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelEstadoLayout.setVerticalGroup(
            jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalir.setBackground(new java.awt.Color(255, 51, 51));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelPrincipalLayout = new javax.swing.GroupLayout(jpPanelPrincipal);
        jpPanelPrincipal.setLayout(jpPanelPrincipalLayout);
        jpPanelPrincipalLayout.setHorizontalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpPanelMasajista, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addComponent(jpPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jpPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPanelTablaSecundaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpPanelPrincipalLayout.setVerticalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpPanelTablaSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubirActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        if(validarCampos()== true){
            masajistas.agregarMasajista(m);
            cargarTabla();
            vaciarCampos();
            inhabilitarCampos();
        }
        
    }//GEN-LAST:event_jbSubirActionPerformed

    private void jtTablaMasajistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaMasajistasMouseClicked
        // TODO add your handling code here:
        cargarCampos(); 
        habilitarCampos();
        txtMatricula.setEnabled(false);
    }//GEN-LAST:event_jtTablaMasajistasMouseClicked

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        if(validarCampos() == true){
            masajistas.actualizarMasajista(m);
            cargarTabla();
            vaciarCampos();
            inhabilitarCampos();
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
        if(validarCampos() == true){
           masajistas.borrarMasajista(m.getMatricula());
           cargarTabla();
           vaciarCampos();
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
        if(validarCampos() == true){
            masajistas.darDeAlta(m.getMatricula());
            cargarTabla();
            vaciarCampos();
        }
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
            if(validarCampos() == true){
            masajistas.darDeBaja(m.getMatricula());
            cargarTabla();
            vaciarCampos();
            }
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jcbEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEspecialidadesActionPerformed
        // TODO add your handling code here:
        String especialidad = jcbEspecialidades.getSelectedItem().toString();
        cargarTablaEspecialidad(especialidad);
    }//GEN-LAST:event_jcbEspecialidadesActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        vaciarCampos();
        habilitarCampos();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEstadoActionPerformed

    private void txtNumeroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTActionPerformed

    private void txtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSubir;
    private javax.swing.JComboBox<String> jcbEspecialidades;
    private javax.swing.JPanel jpPanelBotones1;
    private javax.swing.JPanel jpPanelBotones2;
    private javax.swing.JPanel jpPanelEstado;
    private javax.swing.JPanel jpPanelInfoMasajista;
    private javax.swing.JPanel jpPanelMasajista;
    private javax.swing.JPanel jpPanelPrincipal;
    private javax.swing.JPanel jpPanelTabla;
    private javax.swing.JPanel jpPanelTablaSecundaria;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTable jtTablaMasajistaEspecialidad;
    private javax.swing.JTable jtTablaMasajistas;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtNumeroT;
    // End of variables declaration//GEN-END:variables

//TABLA..........................................................
public void cargarModelo(){
    modeloT.addColumn("Matricula");
    modeloT.addColumn("Nombre Completo");
    modeloT.addColumn("NumeroTelefonico");
    modeloT.addColumn("Especialidad");
    modeloT.addColumn("¿Ocupado?");
    jtTablaMasajistas.setModel(modeloT);
    
}    

public void cargarModeloS(){
    modeloTSec.addColumn("Matricula");
    modeloTSec.addColumn("Nombre Completo");
    modeloTSec.addColumn("Especialidad");
    modeloTSec.addColumn("¿Ocupado?");
    jtTablaMasajistaEspecialidad.setModel(modeloTSec);
}
public void cargarTabla(){
    Utilitario.limpiarTabla(modeloT);
    for(Masajista ma: masajistas.mostrarMasajistas()){
        modeloT.addRow(new Object[]{ma.getMatricula(),ma.getNombreCompleto(),ma.getNumeroT(),ma.getEspecialidad(),ma.isEstado()});
    }
}

private void cargarTablaEspecialidad(String especialidad){
    Utilitario.limpiarTabla(modeloTSec);
    for(Masajista ma: masajistas.mostrarPorEspecialidad(especialidad)){
        modeloTSec.addRow(new Object[]{ma.getMatricula(),ma.getNombreCompleto(),ma.getEspecialidad(),ma.isEstado()});
    }
}

    
//CAMPOS TEXTFIELD..........................................................    
private boolean validarCampos(){

    if(txtMatricula.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese la matricula!!!!!");
    } else if(txtNombreC.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el Nombre completo!!!!!");
    } else if(txtNumeroT.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el numero Telefonico!!!!!");
    }   else if(txtEspecialidad.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese la especialidad!!!!!");
    }else{
        try{
        
        String nombreC = txtNombreC.getText();
        String especialidad = txtEspecialidad.getText();
        int matricula = Integer.parseInt(txtMatricula.getText());
        int numeroT = Integer.parseInt(txtNumeroT.getText());
        m.setMatricula(matricula);
        m.setNumeroT(numeroT);
        m.setEspecialidad(especialidad);
        m.setNombreCompleto(nombreC);
        m.setEstado(true);
 
        
        return true;
        
        }catch(java.lang.NumberFormatException error){
        JOptionPane.showMessageDialog(null, "Ingrese los datos en el formato adecuado!!!!!");
        }
    }
       return false;
       
    }
private void vaciarCampos(){
    txtNombreC.setText("");
    txtNumeroT.setText("");
    txtEspecialidad.setText("");
    txtMatricula.setText("");
}


private void inhabilitarCampos(){
    txtMatricula.setEnabled(false);
    txtNombreC.setEnabled(false);
    txtNumeroT.setEnabled(false);
    txtEspecialidad.setEnabled(false);

}

private void habilitarCampos(){
    txtMatricula.setEnabled(true);
    txtNombreC.setEnabled(true);
    txtNumeroT.setEnabled(true);
    txtEspecialidad.setEnabled(true);
}
//METODO ACTUALIZAR
private void cargarCampos(){
    int filaS = jtTablaMasajistas.getSelectedRow();
    int id = (Integer) jtTablaMasajistas.getValueAt(filaS, 0);
    String matricula =  String.valueOf(jtTablaMasajistas.getValueAt(filaS, 0));
    String nombreC = String.valueOf(jtTablaMasajistas.getValueAt(filaS, 1));
    String numeroT = String.valueOf(jtTablaMasajistas.getValueAt(filaS, 2));
    String especialidad = String.valueOf(jtTablaMasajistas.getValueAt(filaS, 3));
    boolean estados = Boolean.parseBoolean(jtTablaMasajistas.getValueAt(filaS, 4).toString());
    
    txtMatricula.setText(matricula);
    txtNombreC.setText(nombreC);
    txtNumeroT.setText(numeroT);
    txtEspecialidad.setText(especialidad);
    
    if(estados == true){
        jbAlta.setEnabled(false);
        jbBaja.setEnabled(true);
        jtEstado.setBackground(verdeActivo);
        jtEstado.setText("Libre");
    }else if(estados == false){
        jbAlta.setEnabled(true);
        jbBaja.setEnabled(false);
        jtEstado.setBackground(rojoInactivo);
        jtEstado.setText("Ocupado");
    }
}
//METODO SELECT* FROM masajista WHERE especialidad LIKE '%tipo%'
private void cargarCombo(){
    jcbEspecialidades.addItem("Facial");
    jcbEspecialidades.addItem("Corporal");
    jcbEspecialidades.addItem("Relajacion");
    jcbEspecialidades.addItem("Estetico");
   
}


}

