
package Visual;

import Control.MasajistasData;
import Entidades.Masajista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GestionMasajista extends javax.swing.JInternalFrame {

    MasajistasData masajistas = new MasajistasData();
    private boolean estado;
    Masajista m = new Masajista();
    private DefaultTableModel modeloT = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila, int columna){ 
        return false;
    }
    };
   
   
    public GestionMasajista() {
        initComponents();
        cargarModelo();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpEstados = new javax.swing.ButtonGroup();
        jpPanelPrincipal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpPanelMasajista = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbAlta = new javax.swing.JRadioButton();
        jrbBaja = new javax.swing.JRadioButton();
        txtMatricula = new javax.swing.JTextField();
        txtNombreC = new javax.swing.JTextField();
        txtNumeroT = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbSubir = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcbEspecialidades = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jpPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaMasajistas = new javax.swing.JTable();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(560, 605));

        jpPanelPrincipal.setBackground(new java.awt.Color(102, 153, 255));
        jpPanelPrincipal.setPreferredSize(new java.awt.Dimension(550, 605));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MASAJISTAS");

        jpPanelMasajista.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelMasajista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jpPanelMasajista.setPreferredSize(new java.awt.Dimension(515, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Matricula");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre completo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de Telefono");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Especialidad");

        bgpEstados.add(jrbAlta);
        jrbAlta.setForeground(new java.awt.Color(255, 255, 255));
        jrbAlta.setText("Alta");
        jrbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAltaActionPerformed(evt);
            }
        });

        bgpEstados.add(jrbBaja);
        jrbBaja.setForeground(new java.awt.Color(255, 255, 255));
        jrbBaja.setText("Baja");
        jrbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBajaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado");

        jbSubir.setBackground(new java.awt.Color(102, 255, 102));
        jbSubir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbSubir.setText("Subir");
        jbSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubirActionPerformed(evt);
            }
        });

        jbActualizar.setBackground(new java.awt.Color(102, 204, 255));
        jbActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbBorrar.setBackground(new java.awt.Color(255, 102, 102));
        jbBorrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(255, 153, 153));
        jbSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Especialidad");

        jcbEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especialidades" }));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Masajista");

        javax.swing.GroupLayout jpPanelMasajistaLayout = new javax.swing.GroupLayout(jpPanelMasajista);
        jpPanelMasajista.setLayout(jpPanelMasajistaLayout);
        jpPanelMasajistaLayout.setHorizontalGroup(
            jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jrbAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbBaja))
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbEspecialidades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpPanelMasajistaLayout.setVerticalGroup(
            jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelMasajistaLayout.createSequentialGroup()
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbAlta)
                            .addComponent(jrbBaja)
                            .addComponent(jLabel5)))
                    .addGroup(jpPanelMasajistaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPanelMasajistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        jpPanelTabla.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelTabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jpPanelTabla.setPreferredSize(new java.awt.Dimension(514, 251));

        jtTablaMasajistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaMasajistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaMasajistasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaMasajistas);

        javax.swing.GroupLayout jpPanelTablaLayout = new javax.swing.GroupLayout(jpPanelTabla);
        jpPanelTabla.setLayout(jpPanelTablaLayout);
        jpPanelTablaLayout.setHorizontalGroup(
            jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpPanelTablaLayout.setVerticalGroup(
            jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        jbAlta.setBackground(new java.awt.Color(255, 255, 153));
        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setBackground(new java.awt.Color(255, 153, 204));
        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelPrincipalLayout = new javax.swing.GroupLayout(jpPanelPrincipal);
        jpPanelPrincipal.setLayout(jpPanelPrincipalLayout);
        jpPanelPrincipalLayout.setHorizontalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPanelMasajista, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addComponent(jpPanelTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpPanelPrincipalLayout.setVerticalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAltaActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        estado = true;
    }//GEN-LAST:event_jrbAltaActionPerformed

    private void jrbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBajaActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        estado = false;
    }//GEN-LAST:event_jrbBajaActionPerformed

    private void jbSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubirActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        if(validarCampos()== true){
            masajistas.agregarMasajista(m);
            cargarTabla();
            vaciarCampos();
        }
        
    }//GEN-LAST:event_jbSubirActionPerformed

    private void jtTablaMasajistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaMasajistasMouseClicked
        // TODO add your handling code here:
        cargarCampos(); 
    }//GEN-LAST:event_jtTablaMasajistasMouseClicked

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        if(validarCampos() == true){
            masajistas.actualizarMasajista(m);
            cargarTabla();
            vaciarCampos();
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        
        if(validarCampos()== true){
            masajistas.borrarMasajista(m.getMatricula());
            cargarTabla();
            vaciarCampos();
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
        if(validarCampos()== true){
            masajistas.darDeAlta(m.getMatricula());
            cargarTabla();
            vaciarCampos();
        }
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
        if(validarCampos()== true){
            masajistas.darDeBaja(m.getMatricula());
            cargarTabla();
            vaciarCampos();
        }
        
    }//GEN-LAST:event_jbBajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpEstados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSubir;
    private javax.swing.JComboBox<String> jcbEspecialidades;
    private javax.swing.JPanel jpPanelMasajista;
    private javax.swing.JPanel jpPanelPrincipal;
    private javax.swing.JPanel jpPanelTabla;
    private javax.swing.JRadioButton jrbAlta;
    private javax.swing.JRadioButton jrbBaja;
    private javax.swing.JTable jtTablaMasajistas;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtNumeroT;
    // End of variables declaration//GEN-END:variables

//TABLA..........................................................
public void cargarModelo(){
    modeloT.addColumn("Matricula");
    modeloT.addColumn("Nombre Completo");
    modeloT.addColumn("NumeroTelefonico");
    modeloT.addColumn("Especialidad");
    modeloT.addColumn("¿Ocupado?");
    jtTablaMasajistas.setModel(modeloT);
}    
public void cargarTabla(){
    borrarFilas();
    for(Masajista ma: masajistas.mostrarMasajistas()){
        modeloT.addRow(new Object[]{ma.getMatricula(),ma.getNombreCompleto(),ma.getNumeroT(),ma.getEspecialidad(),ma.isEstado()});
    }
}
public void borrarFilas(){
    int indice = jtTablaMasajistas.getRowCount() -1;
    
    for (int i = indice ; i >= 0; i--) {
        modeloT.removeRow(i);
    }
}
    
//CAMPOS TEXTFIELD..........................................................    
private boolean validarCampos(){

    if(txtMatricula.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese la matricula!!!!!");
    } else if(txtNombreC.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el Nombre completo!!!!!");
    } else if(txtNumeroT.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el numero Telefonico!!!!!");
    }   else if(txtEspecialidad.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese la especialidad!!!!!");
    }else{
        try{
        String nombreC = txtNombreC.getText();
        String especialidad = txtEspecialidad.getText();
        int matricula = Integer.parseInt(txtMatricula.getText());
        int numeroT = Integer.parseInt(txtNumeroT.getText());
        m.setMatricula(matricula);
        m.setNumeroT(numeroT);
        m.setEspecialidad(especialidad);
        m.setNombreCompleto(nombreC);
        m.setEstado(estado);
 
        
        return true;
        
        }catch(java.lang.NumberFormatException error){
        JOptionPane.showMessageDialog(null, "Ingrese los datos en el formato adecuado!!!!!");
        }
    }
       return false;
       
    }
private void vaciarCampos(){
    txtNombreC.setText("");
    txtNumeroT.setText("");
    txtEspecialidad.setText("");
    txtMatricula.setText("");
    txtNumeroT.setText("");
    bgpEstados.clearSelection();
}
//METODO ACTUALIZAR
private void cargarCampos(){
    int filaS = jtTablaMasajistas.getSelectedRow();
    
    String matricula =  String.valueOf(jtTablaMasajistas.getValueAt(filaS, 0));
    String nombreC = String.valueOf(jtTablaMasajistas.getValueAt(filaS, 1));
    String numeroT = String.valueOf(jtTablaMasajistas.getValueAt(filaS, 2));
    String especialidad = String.valueOf(jtTablaMasajistas.getValueAt(filaS, 3));
    boolean estados = Boolean.parseBoolean(jtTablaMasajistas.getValueAt(filaS, 4).toString());
    
    txtMatricula.setText(matricula);
    txtNombreC.setText(nombreC);
    txtNumeroT.setText(numeroT);
    txtEspecialidad.setText(especialidad);
    
}
//METODO SELECT* FROM masajista WHERE especialidad LIKE '%tipo%'
private void cargarCombo(){
    jcbEspecialidades.addItem("Facial");
    jcbEspecialidades.addItem("Corporal");
    jcbEspecialidades.addItem("Relajacion");
    jcbEspecialidades.addItem("Estetico");
   
}

}

