
package Visual;

import Control.*;
import Entidades.*;
import java.awt.Color;
import java.time.LocalDate;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GestionSpa extends javax.swing.JInternalFrame {
    
    
    //colores para el texfield de estado
    Color verdeActivo = new Color(200,242,183);
    Color rojoInactivo = new Color(245,164,164);
    //clases data
    DiaSPAData dias = new DiaSPAData();
    ClientesData clientes = new ClientesData();
    //objeto que sirve para poder asignarles atributos y luego enviarlos a la base de datos
    DiaSpa d = new DiaSpa();
    
    
    private DefaultTableModel modeloT = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila, int columna){ 
        return false;
    }
    };
    
    public GestionSpa() {
        initComponents();
        cargarCombo();
        cargarModelo();
        cargarTabla();
        ajusteDeFecha();
        jbActualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPanelPrincipal = new javax.swing.JPanel();
        jpPanelDiaSpa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFecha = new javax.swing.JPanel();
        jdtFecha = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcbClientes = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jbActualizar = new javax.swing.JButton();
        jbSubir = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtPreferencias = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jpPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaDiaS = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jpPanelBotones = new javax.swing.JPanel();
        jbBorrar = new javax.swing.JButton();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jpPanelInformacionC = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtNumeroT = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jpPanelEstado = new javax.swing.JPanel();
        jtEstado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jpPanelPrincipal.setBackground(new java.awt.Color(102, 153, 255));

        jpPanelDiaSpa.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelDiaSpa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agende su dia de spa");

        jPanelFecha.setBackground(new java.awt.Color(0, 102, 153));
        jPanelFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jdtFecha.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Agende el dia");

        javax.swing.GroupLayout jPanelFechaLayout = new javax.swing.GroupLayout(jPanelFecha);
        jPanelFecha.setLayout(jPanelFechaLayout);
        jPanelFechaLayout.setHorizontalGroup(
            jPanelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelFechaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelFechaLayout.setVerticalGroup(
            jPanelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jdtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clientes disponibles");

        jcbClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione a un cliente" }));
        jcbClientes.setToolTipText("");
        jcbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jcbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jbActualizar.setBackground(new java.awt.Color(102, 204, 255));
        jbActualizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbSubir.setBackground(new java.awt.Color(153, 255, 153));
        jbSubir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbSubir.setText("Subir");
        jbSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubirActionPerformed(evt);
            }
        });

        jbNuevo.setBackground(new java.awt.Color(204, 215, 255));
        jbNuevo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPreferencias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPreferencias.setToolTipText("Por EJ: (Facial, Corporal, Especializado, Relajacion, Estetico)");
        txtPreferencias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrese sus preferencias");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpPanelDiaSpaLayout = new javax.swing.GroupLayout(jpPanelDiaSpa);
        jpPanelDiaSpa.setLayout(jpPanelDiaSpaLayout);
        jpPanelDiaSpaLayout.setHorizontalGroup(
            jpPanelDiaSpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelDiaSpaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelDiaSpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelDiaSpaLayout.setVerticalGroup(
            jpPanelDiaSpaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelDiaSpaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpPanelTabla.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelTabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jtTablaDiaS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaDiaS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaDiaSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaDiaS);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dias de spa agendados");

        jpPanelBotones.setBackground(new java.awt.Color(0, 102, 153));
        jpPanelBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbBorrar.setBackground(new java.awt.Color(255, 153, 153));
        jbBorrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbAlta.setBackground(new java.awt.Color(255, 255, 153));
        jbAlta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setBackground(new java.awt.Color(255, 153, 204));
        jbBaja.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        txtID.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");

        javax.swing.GroupLayout jpPanelBotonesLayout = new javax.swing.GroupLayout(jpPanelBotones);
        jpPanelBotones.setLayout(jpPanelBotonesLayout);
        jpPanelBotonesLayout.setHorizontalGroup(
            jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpPanelBotonesLayout.setVerticalGroup(
            jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPanelTablaLayout = new javax.swing.GroupLayout(jpPanelTabla);
        jpPanelTabla.setLayout(jpPanelTablaLayout);
        jpPanelTablaLayout.setHorizontalGroup(
            jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelTablaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpPanelTablaLayout.setVerticalGroup(
            jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpPanelInformacionC.setBackground(new java.awt.Color(102, 213, 255));
        jpPanelInformacionC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre Completo");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edad");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dni");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Numero de Telefono");

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Informacion del cliente seleccionado");

        txtNombreC.setEditable(false);

        txtEdad.setEditable(false);

        txtDNI.setEditable(false);

        txtNumeroT.setEditable(false);

        javax.swing.GroupLayout jpPanelInformacionCLayout = new javax.swing.GroupLayout(jpPanelInformacionC);
        jpPanelInformacionC.setLayout(jpPanelInformacionCLayout);
        jpPanelInformacionCLayout.setHorizontalGroup(
            jpPanelInformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInformacionCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelInformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelInformacionCLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInformacionCLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelInformacionCLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addGroup(jpPanelInformacionCLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelInformacionCLayout.setVerticalGroup(
            jpPanelInformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelInformacionCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPanelInformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPanelInformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelInformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPanelInformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalir.setBackground(new java.awt.Color(255, 51, 51));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jpPanelEstado.setBackground(new java.awt.Color(102, 153, 255));
        jpPanelEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtEstado.setEditable(false);
        jtEstado.setBackground(new java.awt.Color(200, 242, 180));
        jtEstado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jtEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtEstado.setText("Activo");
        jtEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Estado del dia de spa");

        javax.swing.GroupLayout jpPanelEstadoLayout = new javax.swing.GroupLayout(jpPanelEstado);
        jpPanelEstado.setLayout(jpPanelEstadoLayout);
        jpPanelEstadoLayout.setHorizontalGroup(
            jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelEstadoLayout.setVerticalGroup(
            jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPanelPrincipalLayout = new javax.swing.GroupLayout(jpPanelPrincipal);
        jpPanelPrincipal.setLayout(jpPanelPrincipalLayout);
        jpPanelPrincipalLayout.setHorizontalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jpPanelDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpPanelInformacionC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelPrincipalLayout.createSequentialGroup()
                                        .addGap(0, 243, Short.MAX_VALUE)
                                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))))
                .addContainerGap())
        );
        jpPanelPrincipalLayout.setVerticalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPanelDiaSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpPanelInformacionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jpPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpPanelTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesActionPerformed
        // TODO add your handling code here:
        /*El usuario seleccione un ID de un cliente del jcombobox y luego esa informacion procede a mostrarsela en el panel de al lado
            para que ul usario sepa que cliente es.*/
        cargarCliente();
    }//GEN-LAST:event_jcbClientesActionPerformed

    private void jtTablaDiaSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaDiaSMouseClicked
        // TODO add your handling code here:
        /*este metodo permite que el usuario a la hora de (actualizar, borrar, alta logica, baja logica), les ingrese su respectivas id
        y se le asigne al objeto d(DiaSpa) y luego con ese dato pueda modificar la fila(tupla) deseada
            este metodo es esencial para el funcionamiento de los demas metodos (alta, baja, actualizar, borrar)*/
        
        cargarCampos();
        habilitarCampos();
        jbActualizar.setEnabled(true);
        jbSubir.setEnabled(false);
    }//GEN-LAST:event_jtTablaDiaSMouseClicked

    private void jbSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubirActionPerformed
        // TODO add your handling code here:
        /*si el metodo validar campo retorna true, indica que se pudo parsear y asignar los atributos al objeto d(DiaSpa)
          y se puede proceder a subir esos mismos datos a la BD spa_relax*/
        if(validarCampos()== true){
                dias.crearDiaSpa(d);
                cargarTabla();
                vaciarCampos();
                inhabilitarCampos();
                jbSubir.setEnabled(false);
            }
    }//GEN-LAST:event_jbSubirActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
            if(d.getCodPack() == -1){
                JOptionPane.showMessageDialog(null, "Seleccione un dia para borrar");
            }else{
            dias.borrarDiaSpa(d.getCodPack());
            cargarTabla();
            vaciarCampos();
            
            jbActualizar.setEnabled(false);
            jbSubir.setEnabled(true);
            }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        if(validarCampos()==true){
            dias.actualizarDiaSpa(d);
            cargarTabla();
            vaciarCampos();
            inhabilitarCampos();
            
            jbActualizar.setEnabled(false);
            jbSubir.setEnabled(true);
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
        if(d.getCodPack()== -1){
            JOptionPane.showMessageDialog(null, "Seleccione algun dia de spa");
        }else{
        dias.altaLogicaDiaSpa(d);
        cargarTabla();
        vaciarCampos();
        
        jbActualizar.setEnabled(false);
        jbSubir.setEnabled(true);
        }
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
        if(d.getCodPack()== -1){
            JOptionPane.showMessageDialog(null, "Seleccione algun dia de spa");
        }else{
        dias.bajaLogicaDiaSpa(d);
        cargarTabla();
        vaciarCampos();
        
        jbActualizar.setEnabled(false);
        jbSubir.setEnabled(true);
       }
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        vaciarCampos();
        habilitarCampos();
        
        jbActualizar.setEnabled(false);
        jbSubir.setEnabled(true);
    }//GEN-LAST:event_jbNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSubir;
    private javax.swing.JComboBox<String> jcbClientes;
    private com.toedter.calendar.JDateChooser jdtFecha;
    private javax.swing.JPanel jpPanelBotones;
    private javax.swing.JPanel jpPanelDiaSpa;
    private javax.swing.JPanel jpPanelEstado;
    private javax.swing.JPanel jpPanelInformacionC;
    private javax.swing.JPanel jpPanelPrincipal;
    private javax.swing.JPanel jpPanelTabla;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTable jtTablaDiaS;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtNumeroT;
    private javax.swing.JTextField txtPreferencias;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        //carga el jcombobox con todos los clientes sin importar su estado.
        for (Cliente c : clientes.mostrarClientesActivos()) {
            String id = String.valueOf(c.getCodCli()+" - "+ c.getNombreC());
            jcbClientes.addItem(id);
        }
    }

    private void cargarModelo() {
        modeloT.addColumn("CodPack");
        modeloT.addColumn("Fecha");
        modeloT.addColumn("Cliente");
        modeloT.addColumn("Preferencias");
        modeloT.addColumn("Estado");
        jtTablaDiaS.setModel(modeloT);
    }

    private void cargarTabla() {
        Utilitario.limpiarTabla(modeloT);
        for (DiaSpa diaS : dias.cargarTodosDiaSpa()) {
            modeloT.addRow(new Object[]{diaS.getCodPack(), diaS.getFecha(), diaS.getCliente().getCodCli(), diaS.getPrefencias(), diaS.isEstado()});
        }
    }

//este metodo es de tipo boolean porque me permite reutilizarlo devuelta a la hora de actualizar.
    private boolean validarCampos() {
        ClientesData clientes = new ClientesData();
        
        /*este metodo verifica si cada campo del jTextField esta vacio o contiene algun dato.
      en caso de que un campo este sin rellenar entra en un bloque if o if else y se le muestra una ventana emergente
     en donde le falta llenar y va hasta el final del metodo para retornar false*/
        
        if (txtNombreC.getText().isEmpty()) {
            /*solamente verifico si algun campo de la informacion cliente esta vacia.
              si esta vacia se entiende que el usuario no selecciono ningun cliente*/
            JOptionPane.showMessageDialog(null, "Seleccione un cliente!!!!", "Cuidado", JOptionPane.WARNING_MESSAGE);
            
        } else if (jdtFecha.getDate() == null) {
            
            JOptionPane.showMessageDialog(null, "Ingrese la fecha", "Cuidado", JOptionPane.WARNING_MESSAGE);
            
        } else if (txtPreferencias.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Ingrese sus preferencias", "Cuidado", JOptionPane.WARNING_MESSAGE);
            
        }else {
            /*en caso de que todos los campos hayan comprobado que tienen algun dato,
        se procede a parsearlos a variables que sean faciales de identificar.
        en caso de haber un error en tema de parseo de string a int o un datetime excepcion
        sale sus respectivos carteles indicando la falla*/
            try {
                //patron que identifica caracteres alfabeticos junto con el punto  y coma.
                String rgX="[-,.A-Za-z]";
               //cliente es el id con espacios pero sin el nombreCompleto 
                String cliente = jcbClientes.getSelectedItem().toString().replaceAll(rgX, "");
                //el string id es el numero identificador limpio sin espacios.
                String id = cliente.replace(" ", "");
                int idC = Integer.valueOf(id);
                
                Cliente c = clientes.buscarCliente(idC);
                
                String preferencias = txtPreferencias.getText();
                

                /*saco los valores del jDateChooser, para luego con esos datos formar un LocalDate
                y poder integrarlo al atributo de DiaSpa que es de tipo LocalDateTime*/
                
                int año = jdtFecha.getCalendar().get(Calendar.YEAR);
                int mes = jdtFecha.getCalendar().get(Calendar.MONTH) + 1;
                int dia = jdtFecha.getCalendar().get(Calendar.DAY_OF_MONTH) ;
                
                LocalDate fecha = LocalDate.of(año, mes, dia);
                
                /*cada dato que el usuario haya ingresado se le asigna al objeto d(DiaSpa). menos el id que no es necesario es auto_incremental*/
                
                d.setCliente(c);
                d.setPrefencias(preferencias);
                d.setFecha(fecha);
                d.setMonto(0);
                d.setEstado(true);

                return true;

            } catch (java.lang.NumberFormatException error) {
                
                JOptionPane.showMessageDialog(null, error.getMessage());
                
            } catch (java.time.DateTimeException error) {
                
                JOptionPane.showMessageDialog(null, "Ingrese en el formato correcto la fecha (14 NOV 2025)","Error al ingresar la fecha", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
        return false;
        
    }

    private void vaciarCampos() {
        //setea los jTextField a "" y el jCombBox al indice  0, la jdtCalendar a null.
        
        txtID.setText("");
        txtPreferencias.setText("");
        txtNombreC.setText("");
        txtEdad.setText("");
        txtDNI.setText("");
        txtNumeroT.setText("");
        
        jtEstado.setText("Activo");
        jtEstado.setBackground(verdeActivo);
        
        jcbClientes.setSelectedIndex(0);
        jtTablaDiaS.clearSelection();
        
        jdtFecha.setDate(null);

        //setearlo al -1 me sirve para verificar si al seleccionar y cargar los campos y luego poner nuevo tiene seleccionado alguno
        d.setCodPack(-1);
        jbAlta.setEnabled(true);
        jbBaja.setEnabled(true);
    }

    private void cargarCampos() {
        
        
        int filaS = jtTablaDiaS.getSelectedRow();
        //mediante estas dos variables le asigno al objeto d(DiaSpa) las dos llaves foraneas.
        int codPack = (Integer) jtTablaDiaS.getValueAt(filaS, 0);
        int idC = (Integer) jtTablaDiaS.getValueAt(filaS, 2);
        //ya con el codPack(Key Primary o llave primaria) podemos dar de alta, baja, borra y actualizar. debido a que se lo setea al objeto d(DiaSpa)
            Cliente c = clientes.buscarCliente(idC);
            
            txtNombreC.setText(c.getNombreC());
            txtEdad.setText(String.valueOf(c.getEdad()));
            txtDNI.setText(String.valueOf(c.getDni()));
            txtNumeroT.setText(String.valueOf(c.getTelefono()));
        
        
        d.setCodPack(codPack);
        
        /*creamos un objeto dia mediante el metodo cargarDiaSpa que nos retorna el diaDeSpa especifico mediante el codPack.
      para luego con los metodos get, obtener los datos y ponerlos en los jTextField*/
        DiaSpa dia = dias.cargarDiaSpa(codPack);

        //Todas estas variables sirven para poder setear los jTextField y por ende rellenar sus campos.
        String preferencia = dia.getPrefencias();
        String id = String.valueOf(dia.getCodPack());
        jcbClientes.setSelectedItem(c.getCodCli()+" - "+ c.getNombreC());
        LocalDate fecha = dia.getFecha();
        jdtFecha.setDate(Date.valueOf(fecha));
        txtPreferencias.setText(preferencia);
        txtID.setText(id);

        //metodo que habilita o inhabilita segun el estado del objeto seleccionado.
        
        boolean estado = Boolean.valueOf(jtTablaDiaS.getValueAt(filaS, 4).toString());
        
        if (estado == true) {
            
            jbAlta.setEnabled(false);
            jbBaja.setEnabled(true);
            jtEstado.setText("Activo");
            jtEstado.setBackground(verdeActivo);
            
        } else if (estado == false) {
            
            jbAlta.setEnabled(true);
            jbBaja.setEnabled(false);
            jtEstado.setText("Inactivo");
            jtEstado.setBackground(rojoInactivo);
            
        }
        

    }
    private void inhabilitarCampos() {
        
        txtPreferencias.setEnabled(false);
        jdtFecha.setEnabled(false);
        jcbClientes.setEnabled(false);
        
    }

    private void habilitarCampos() {
        
        txtPreferencias.setEnabled(true);
        jdtFecha.setEnabled(true);
        jcbClientes.setEnabled(true);
        jbSubir.setEnabled(true);
        
    }

    private void cargarCliente() {
        /*esto patron regeX identifica un grupo de caracter alfabetico junto con el guion y coma.
          esta cadena va a servir para poder extraer el ID de tipo int solo y poder cargar la informacion del cliente*/
        String rgX="[-,.A-Za-z]";
        
        /*metodo que funciona en conjunto al Jcombobox.
        el usario elije el id y carga informacion que este relacionada al id*/
        
        //si el item seleccionado no es igual a ID clientes. que proceda a cargar la info. en caso contrario no carga nada.
        if (!jcbClientes.getSelectedItem().toString().equals("Seleccione a un cliente")) {
            
            //mediante el rgX de arriba remplazamos todos los caracter alfabeticos junto con el - a espacioes en blanco
            String cliente = jcbClientes.getSelectedItem().toString().replaceAll(rgX, "");
            
            //elimina los espacios en blanco
            String id = cliente.replace(" ", "");
            
            //se procede al parseo 
            int idC = Integer.valueOf(id);
            Cliente c = clientes.buscarCliente(idC);
            //se carga la informacion
            txtNombreC.setText(c.getNombreC());
            txtEdad.setText(String.valueOf(c.getEdad()));
            txtDNI.setText(String.valueOf(c.getDni()));
            txtNumeroT.setText(String.valueOf(c.getTelefono()));
            
        }
        
    }
    
   /* private boolean tarjetaDeCredito(){
            //patron 1234 1234 1234 1243.
            String formato ="\\d{4}+\s+\\d{4}+\s+\\d{4}+\s+\\d{4}";
            String tarjeta;
            
            //muestra un input dialog que el usuario debe escribir los digitos de su tarjeta para poder abonar
            tarjeta = JOptionPane.showInputDialog("Ingrese los digitos de su tarjeta antes de poder abonar EJ(1234 1234 1234 1234)");
            //si la tarjeta no coincide con el formato entonces se le pide el ingreso nuevamente
            if(!tarjeta.matches(formato)){
                JOptionPane.showMessageDialog(null, "Ingrese una tarjeta valida");
            }else{
                System.out.println("su tarjeta fue registrada con exito!!!!");
                return true;
            }
           
            return false;
    }
   */
    
    private void ajusteDeFecha(){
        //seteo el rango seleccionable del jDateChooser
        Date fechaActual = Date.valueOf(LocalDate.now());
        Date fechaFinLaborable = Date.valueOf(LocalDate.of(2025, 12, 25));
        jdtFecha.setSelectableDateRange(fechaActual, fechaFinLaborable);
        
    }
    
    private void unMensaje(){
    JOptionPane.showMessageDialog(rootPane, closable);
    
    }
}
