
package Visual;
import Control.*;
import javax.swing.JScrollPane;
import Entidades.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class SpaPrincipal extends javax.swing.JFrame {
    //Clases data
     TratamientosData tratamientos = new TratamientosData();
     MasajistasData masajistas = new MasajistasData();
     SesionData sesiones = new SesionData();
     InstalacionesData instalaciones = new InstalacionesData();
     ClientesData clientes = new ClientesData();
     
    //MODELO DE TABLA: INSTALACION
    private DefaultTableModel modeloTablaInstalacion = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    //MODELO DE TABLA: TRATAMIENTO
    private DefaultTableModel modeloTablaTratamientos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    //MODELO DE TABLA: MASAJISTA
    private DefaultTableModel modeloTablaMasajistas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    //MODELO DE TABLA: SESION
    private DefaultTableModel modeloTablaSesiones = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    public SpaPrincipal() {
        initComponents();
        cargarDiseñosDeTablas();
        cargarTablas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jpPanelSecundario = new javax.swing.JPanel();
        jpSesiones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtSesiones = new javax.swing.JTable();
        jpMasajistas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtMasajistas = new javax.swing.JTable();
        jpPanelPrincipal = new javax.swing.JPanel();
        jpTratamientos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTratamientos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jpDetallesT = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtaDetallesT = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jpInstalaciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtInstalaciones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jpDetallesI = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtaDetallesI = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jmbMenu = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmDiaSpa = new javax.swing.JMenu();
        jmiDiaSpa = new javax.swing.JMenuItem();
        jmSesion = new javax.swing.JMenu();
        jmiSesion = new javax.swing.JMenuItem();
        jmGestionSpa = new javax.swing.JMenu();
        jmiInstalaciones = new javax.swing.JMenuItem();
        jmiMasajistas = new javax.swing.JMenuItem();
        jmiTratamientos = new javax.swing.JMenuItem();
        jmCerrar = new javax.swing.JMenu();
        jmiCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Escritorio.setPreferredSize(new java.awt.Dimension(900, 700));

        jpPanelSecundario.setBackground(new java.awt.Color(165, 189, 210));
        jpPanelSecundario.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 153, 204)));

        jpSesiones.setBackground(new java.awt.Color(0, 153, 153));
        jpSesiones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpSesiones.setPreferredSize(new java.awt.Dimension(350, 230));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sesiones en curso");

        jScrollPane5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        jtSesiones.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jtSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jtSesiones);

        javax.swing.GroupLayout jpSesionesLayout = new javax.swing.GroupLayout(jpSesiones);
        jpSesiones.setLayout(jpSesionesLayout);
        jpSesionesLayout.setHorizontalGroup(
            jpSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSesionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpSesionesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpSesionesLayout.setVerticalGroup(
            jpSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSesionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpMasajistas.setBackground(new java.awt.Color(0, 153, 153));
        jpMasajistas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpMasajistas.setPreferredSize(new java.awt.Dimension(350, 230));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Masajistas disponibles");

        jScrollPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        jtMasajistas.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jtMasajistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtMasajistas);

        javax.swing.GroupLayout jpMasajistasLayout = new javax.swing.GroupLayout(jpMasajistas);
        jpMasajistas.setLayout(jpMasajistasLayout);
        jpMasajistasLayout.setHorizontalGroup(
            jpMasajistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMasajistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMasajistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(jpMasajistasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMasajistasLayout.setVerticalGroup(
            jpMasajistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMasajistasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpPanelSecundarioLayout = new javax.swing.GroupLayout(jpPanelSecundario);
        jpPanelSecundario.setLayout(jpPanelSecundarioLayout);
        jpPanelSecundarioLayout.setHorizontalGroup(
            jpPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jpMasajistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpPanelSecundarioLayout.setVerticalGroup(
            jpPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jpPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMasajistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpPanelPrincipal.setBackground(new java.awt.Color(165, 189, 210));
        jpPanelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 153, 204)));

        jpTratamientos.setBackground(new java.awt.Color(0, 153, 153));
        jpTratamientos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        jtTratamientos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jtTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTratamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTratamientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTratamientos);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tratamientos Disponibles");

        jpDetallesT.setBackground(new java.awt.Color(0, 207, 170));
        jpDetallesT.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtaDetallesT.setColumns(20);
        jtaDetallesT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jtaDetallesT.setLineWrap(true);
        jtaDetallesT.setRows(5);
        jtaDetallesT.setWrapStyleWord(true);
        jtaDetallesT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane6.setViewportView(jtaDetallesT);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Detalles");

        javax.swing.GroupLayout jpDetallesTLayout = new javax.swing.GroupLayout(jpDetallesT);
        jpDetallesT.setLayout(jpDetallesTLayout);
        jpDetallesTLayout.setHorizontalGroup(
            jpDetallesTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetallesTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDetallesTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDetallesTLayout.setVerticalGroup(
            jpDetallesTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDetallesTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpTratamientosLayout = new javax.swing.GroupLayout(jpTratamientos);
        jpTratamientos.setLayout(jpTratamientosLayout);
        jpTratamientosLayout.setHorizontalGroup(
            jpTratamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTratamientosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTratamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpDetallesT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTratamientosLayout.setVerticalGroup(
            jpTratamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTratamientosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTratamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpTratamientosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpDetallesT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpInstalaciones.setBackground(new java.awt.Color(0, 153, 153));
        jpInstalaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        jtInstalaciones.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jtInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtInstalaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtInstalacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtInstalaciones);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Instalaciones Disponibles");

        jpDetallesI.setBackground(new java.awt.Color(0, 207, 170));
        jpDetallesI.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtaDetallesI.setColumns(20);
        jtaDetallesI.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jtaDetallesI.setLineWrap(true);
        jtaDetallesI.setRows(5);
        jtaDetallesI.setWrapStyleWord(true);
        jtaDetallesI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane7.setViewportView(jtaDetallesI);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Detalles");

        javax.swing.GroupLayout jpDetallesILayout = new javax.swing.GroupLayout(jpDetallesI);
        jpDetallesI.setLayout(jpDetallesILayout);
        jpDetallesILayout.setHorizontalGroup(
            jpDetallesILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetallesILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDetallesILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jpDetallesILayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDetallesILayout.setVerticalGroup(
            jpDetallesILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetallesILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpInstalacionesLayout = new javax.swing.GroupLayout(jpInstalaciones);
        jpInstalaciones.setLayout(jpInstalacionesLayout);
        jpInstalacionesLayout.setHorizontalGroup(
            jpInstalacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInstalacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInstalacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpDetallesI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpInstalacionesLayout.setVerticalGroup(
            jpInstalacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInstalacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInstalacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpDetallesI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpInstalacionesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpPanelPrincipalLayout = new javax.swing.GroupLayout(jpPanelPrincipal);
        jpPanelPrincipal.setLayout(jpPanelPrincipalLayout);
        jpPanelPrincipalLayout.setHorizontalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelPrincipalLayout.setVerticalGroup(
            jpPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jpInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Escritorio.setLayer(jpPanelSecundario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jpPanelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jpPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jpPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jmClientes.setText("Clientes");

        jmiClientes.setText("Ingreso de datos");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmClientes.add(jmiClientes);

        jmbMenu.add(jmClientes);

        jmDiaSpa.setText("dia Spa");

        jmiDiaSpa.setText("Agende su dia");
        jmiDiaSpa.setToolTipText("");
        jmiDiaSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDiaSpaActionPerformed(evt);
            }
        });
        jmDiaSpa.add(jmiDiaSpa);

        jmbMenu.add(jmDiaSpa);

        jmSesion.setText("Sesion");

        jmiSesion.setText("Gestione su sesion");
        jmiSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSesionActionPerformed(evt);
            }
        });
        jmSesion.add(jmiSesion);

        jmbMenu.add(jmSesion);

        jmGestionSpa.setText("Gestion-SPA");
        jmGestionSpa.setToolTipText("");

        jmiInstalaciones.setText("Gestion - Instalacion");
        jmiInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInstalacionesActionPerformed(evt);
            }
        });
        jmGestionSpa.add(jmiInstalaciones);

        jmiMasajistas.setText("Gestion - Masajistas");
        jmiMasajistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMasajistasActionPerformed(evt);
            }
        });
        jmGestionSpa.add(jmiMasajistas);

        jmiTratamientos.setText("Gestion - Tratamientos");
        jmiTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTratamientosActionPerformed(evt);
            }
        });
        jmGestionSpa.add(jmiTratamientos);

        jmbMenu.add(jmGestionSpa);

        jmCerrar.setText("Cerrar");

        jmiCerrar.setText("Cerrar");
        jmiCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCerrarActionPerformed(evt);
            }
        });
        jmCerrar.add(jmiCerrar);

        jmbMenu.add(jmCerrar);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInstalacionesActionPerformed
        // TODO add your handling code here:
        
        Escritorio.repaint();
        GestionInstalacion gi = new GestionInstalacion();
        gi.setVisible(true);
        Escritorio.add(gi);
        Escritorio.moveToFront(gi);
    }//GEN-LAST:event_jmiInstalacionesActionPerformed

    private void jmiCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiCerrarActionPerformed

    private void jmiMasajistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMasajistasActionPerformed
        // TODO add your handling code here:
        
        Escritorio.repaint();
        GestionMasajista gm = new GestionMasajista();
        gm.setVisible(true);
        Escritorio.add(gm);
        Escritorio.moveToFront(gm);
    }//GEN-LAST:event_jmiMasajistasActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        // TODO add your handling code here:
        
        Escritorio.repaint();
        GestionClientes gc = new GestionClientes();
        gc.setVisible(true);
        Escritorio.add(gc);
        Escritorio.moveToFront(gc);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiDiaSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDiaSpaActionPerformed
        // TODO add your handling code here:
        
        Escritorio.repaint();
        GestionSpa gs = new GestionSpa();
        gs.setVisible(true);
        Escritorio.add(gs);
        Escritorio.moveToFront(gs);
    }//GEN-LAST:event_jmiDiaSpaActionPerformed

    private void jmiSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSesionActionPerformed
                
        Escritorio.repaint();
        VistaSesion vs = new VistaSesion();
        vs.setVisible(true);
        vs.setSize(Escritorio.getSize());
        vs.setMaximizable(true);
        vs.setResizable(true);
        Escritorio.add(vs);
        Escritorio.moveToFront(vs);
        
    }//GEN-LAST:event_jmiSesionActionPerformed

    private void jmiTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTratamientosActionPerformed
        
        Escritorio.repaint();
        VistaTratamientos vt = new VistaTratamientos();
        vt.setVisible(true);
        vt.setSize(Escritorio.getSize());
        vt.setMaximizable(true);
        vt.setResizable(true);
        Escritorio.add(vt);
        Escritorio.moveToFront(vt);
        
    }//GEN-LAST:event_jmiTratamientosActionPerformed

    private void jtTratamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTratamientosMouseClicked
        // TODO add your handling code here:
        
        int filaS = jtTratamientos.getSelectedRow();
        String detalles = jtTratamientos.getValueAt(filaS, 1).toString();
        jtaDetallesT.setText(detalles);
    }//GEN-LAST:event_jtTratamientosMouseClicked

    private void jtInstalacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInstalacionesMouseClicked
        // TODO add your handling code here:
        int filaS = jtInstalaciones.getSelectedRow();
        String detalles = jtInstalaciones.getValueAt(filaS, 1).toString();
        jtaDetallesI.setText(detalles);
    }//GEN-LAST:event_jtInstalacionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JMenu jmCerrar;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmDiaSpa;
    private javax.swing.JMenu jmGestionSpa;
    private javax.swing.JMenu jmSesion;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiCerrar;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiDiaSpa;
    private javax.swing.JMenuItem jmiInstalaciones;
    private javax.swing.JMenuItem jmiMasajistas;
    private javax.swing.JMenuItem jmiSesion;
    private javax.swing.JMenuItem jmiTratamientos;
    private javax.swing.JPanel jpDetallesI;
    private javax.swing.JPanel jpDetallesT;
    private javax.swing.JPanel jpInstalaciones;
    private javax.swing.JPanel jpMasajistas;
    private javax.swing.JPanel jpPanelPrincipal;
    private javax.swing.JPanel jpPanelSecundario;
    private javax.swing.JPanel jpSesiones;
    private javax.swing.JPanel jpTratamientos;
    private javax.swing.JTable jtInstalaciones;
    private javax.swing.JTable jtMasajistas;
    private javax.swing.JTable jtSesiones;
    private javax.swing.JTable jtTratamientos;
    private javax.swing.JTextArea jtaDetallesI;
    private javax.swing.JTextArea jtaDetallesT;
    // End of variables declaration//GEN-END:variables

    private void cargarDiseñosDeTablas() {
        //DISEÑO TABLA: INSTALACION
        modeloTablaInstalacion.addColumn("Nombre");
        modeloTablaInstalacion.addColumn("Detalles de uso");
        modeloTablaInstalacion.addColumn("Precio X 30MIN");
        modeloTablaInstalacion.addColumn("APTO");
        jtInstalaciones.setModel(modeloTablaInstalacion);
        //DISEÑO TABLA: TRATAMIENTO
        modeloTablaTratamientos.addColumn("Nombre");
        modeloTablaTratamientos.addColumn("Detalles");
        modeloTablaTratamientos.addColumn("Costo");
        modeloTablaTratamientos.addColumn("Duracion");
        jtTratamientos.setModel(modeloTablaTratamientos);
        //DISEÑO TABLA: MASAJISTA
        modeloTablaMasajistas.addColumn("Nombre completo");
        modeloTablaMasajistas.addColumn("Especialidad");
        modeloTablaMasajistas.addColumn("Numero de telefono");
        jtMasajistas.setModel(modeloTablaMasajistas);
        //DISEÑO TABLA: Sesion
        modeloTablaSesiones.addColumn("Numero de Sesion");
        modeloTablaSesiones.addColumn("Horario de inicio");
        modeloTablaSesiones.addColumn("Horario de finalizacion");
        jtSesiones.setModel(modeloTablaSesiones);
    }

    private void cargarTablas() {
        
        Utilitario.limpiarTabla(modeloTablaSesiones);
        Utilitario.limpiarTabla(modeloTablaInstalacion);
        Utilitario.limpiarTabla(modeloTablaMasajistas);
        Utilitario.limpiarTabla(modeloTablaTratamientos);

        //tratamientos nombre, detalles del tratamiento costo y duracion
        for (Tratamiento t : tratamientos.mostrarTratamientos()) {
            modeloTablaTratamientos.addRow(new Object[]{t.getNombre(),t.getDetalle(), t.getCosto(), t.getDuracion()});
        }
         //instalaciones ATRIBUTOS: nombre, detallesDeUso, Precio30m y apto.
        for(Instalacion i : instalaciones.mostrarInstalacionesLibres()){
            modeloTablaInstalacion.addRow(new Object[]{i.getNombre(), i.getDetallesUso(), i.getPrecio30M(), i.getApto()});
        }
        //masajistas ATRIBUTOS: nombreC, especialidad, numero de telefono
        for(Masajista m : masajistas.mostrarMasajistasDisponibles()){
            modeloTablaMasajistas.addRow(new Object[]{m.getNombreCompleto(), m.getEspecialidad(), m.getNumeroT()});
        }
        //sesiones ATRIBUTOS: numero de sesion(id), horario de inicio y horario de finalizacion;
        for(Sesion s : sesiones.mostrarTodasSesiones()){
            modeloTablaSesiones.addRow(new Object[]{s.getCodSesion(), s.getFechaIn(), s.getFechaFin()});
        }      

    }    

    
}
